// Generated by CoffeeScript 1.3.3
var explore, fork, __;

__ = require('../i18n');

fork = require("child_process").fork;

explore = {
  process: false,
  index: function(req, res) {
    explore.start();
    res.locals.json.action = "reload";
    return res.json(res.locals.json);
  },
  start: function() {
    var cp;
    if (!explore.process) {
      cp = fork("" + __dirname + "/../explore");
      return cp.on("exit", function() {
        return explore.process = false;
      });
    }
  }
};

module.exports = explore;
