// Generated by CoffeeScript 1.3.3
var language;

language = require('./en');

module.exports = function(string) {
  if (language[string] != null) {
    return language[string];
  } else {
    return string;
  }
};
